ALTER TABLE OPERADOR ADD (
    PERFIL VARCHAR2(20) DEFAULT 'OPERADOR' NOT NULL
);

UPDATE OPERADOR SET PERFIL = 'ADMIN' WHERE LOGIN = 'admin';
UPDATE OPERADOR SET PERFIL = 'OPERADOR' WHERE PERFIL IS NULL;

UPDATE OPERADOR SET SENHA = '{noop}admin123' WHERE LOGIN = 'admin';
UPDATE OPERADOR SET SENHA = '{noop}operador123' WHERE LOGIN = 'operador';
